### ISSUE TITLE
Is it possible to add a button on the admin abandoned carts, that manually sends an email?

### ISSUE THREAD

**Issue by localhosted** [paras89/parassood_abandonedcart#1]
Most abandoned carts plugins are all set to send emails on a timer, but not all abandoned carts are worth pursuing, or even actual abandoned carts (magento sometimes leaves carts as "abandoned", even if the same client made a purchase in the same day).

Is it possible to manually trigger an email while on the abandoned carts grid?

**Comment by paras89** [comment]
This module runs a cron job in the background that checks for each quote which step of checkout the customer went furthest to in a session, checks if there is a campaign/sub-campaign whose stipulations are followed by the particular quote, and in case there is a campaign/sub-campaign configured, it sends the customer an email with a discount code per the settings in the campaign/sub-campaign.

I am afraid, manually triggering an abandoned cart email does not fall within the scope of this module.
Closing this, as this is not an issue!
